#!/usr/bin/env bash
# This script displays user information from /etc/passwd using a while loop and IFS

# Set IFS to colon ':' to parse the fields in /etc/passwd
IFS=':'

# Read /etc/passwd line by line using a while loop
while read -r username password userid groupid user_info home_directory shell
do
    # Extract additional user information
    user_info=$(getent passwd "$username" | cut -d':' -f5)
    
    # Display user information in the specified format
    echo "The user $username is part of the $groupid gang, lives in $home_directory and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd

