#!/usr/bin/env bash
# This script extracts visitor IP and HTTP status code from Apache log using awk
# Using awk to extract and format the IP address and HTTP status code

awk '{print $1 "" $9}' apache-access.log

